import { test, expect } from '@playwright/test';
test('reference layout, project filters, search, and theme work',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'Akash Kushwaha',exact:true})).toBeVisible();
 await expect(page.locator('.cover')).toHaveCSS('height','256px');
 await expect(page.locator('.project-row')).toHaveCount(4);
 await page.getByRole('button',{name:'Explorations',exact:true}).click();
 await expect(page.locator('.project-row')).toHaveCount(1);
 await expect(page.locator('#project-aira')).toContainText('Pre-MVP');
 await page.getByRole('button',{name:'Search portfolio',exact:true}).click();
 await page.getByRole('searchbox').fill('Sci-WebHub');
 await page.getByRole('searchbox').press('Enter');
 await expect(page.locator('#project-dialog')).toBeVisible();
 await expect(page.locator('#project-dialog')).toContainText('deployment');
 await page.keyboard.press('Escape');
 await expect(page.locator('#project-dialog')).not.toBeVisible();
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await page.getByRole('button',{name:'Switch to light theme'}).click();
 await page.reload();
 await expect(page.locator('html')).toHaveAttribute('data-theme','light');
 expect(errors).toEqual([]);
});
test('components and LinkedIn have working actions',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);
 await page.goto('/');
 await page.getByRole('button',{name:'Buttons',exact:true}).click();
 await page.getByRole('button',{name:'Save for later',exact:true}).click();
 await expect(page.getByRole('button',{name:'Saved for later'})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('switch').click();
 await expect(page.getByRole('switch')).toHaveAttribute('aria-checked','false');
 await page.getByRole('button',{name:'Copy npm install ml-uikit'}).click();
 expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('npm install ml-uikit');
 await expect(page.getByRole('link',{name:'Read the post'})).toHaveAttribute('href','https://www.linkedin.com/feed/update/urn:li:activity:7433204217307254784/');
 await page.getByText('Show LinkedIn post',{exact:false}).click();
 await expect(page.locator('#linkedin-frame iframe')).toHaveAttribute('src','https://www.linkedin.com/embed/feed/update/urn:li:activity:7433204217307254784');
 const response=await page.request.get('/Akash_Resume.pdf');expect(response.ok()).toBeTruthy();expect(response.headers()['content-type']).toContain('pdf');
});
test('mobile fits screen and local assets load',async({page})=>{
 await page.setViewportSize({width:390,height:844});
 await page.goto('/');
 await page.evaluate(()=>document.querySelectorAll('img').forEach(i=>i.loading='eager'));
 await expect.poll(()=>page.evaluate(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0))).toBe(true);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Search portfolio',exact:true}).click();
 await expect(page.getByRole('searchbox')).toBeFocused();
 await page.keyboard.press('Escape');
 await expect(page.locator('#search-dialog')).not.toBeVisible();
});

test('full-stack profile and WhatsApp enquiry flow',async({page})=>{
 await page.goto('/');
 await expect(page.locator('#brandhub-experience')).toContainText('The Branding Club');
 await expect(page.locator('#project-grid')).not.toContainText('BrandHub');
 await expect(page.locator('#experience')).toContainText('AWS EC2');
 await expect(page.locator('#experience')).toContainText('40%');
 await expect(page.getByRole('link',{name:'Machli · Google Play'})).toHaveAttribute('href',/id=ai.rfis.machli/);
 await expect(page.locator('footer')).not.toContainText('Design reference');
 await expect(page.locator('#contact-ready')).toBeHidden();
 await page.getByLabel('Your name',{exact:true}).fill('A recruiter & team');
 await page.getByLabel('What brings you here?').selectOption('An AI product idea');
 await page.getByLabel('Your message',{exact:true}).fill('Build APIs + AI? Let’s discuss <scope>.');
 await page.getByRole('button',{name:'Prepare WhatsApp message'}).click();
 const link=page.locator('#contact-whatsapp');
 await expect(link).toBeFocused();
 const url=new URL(await link.getAttribute('href'));
 expect(url.origin+url.pathname).toBe('https://wa.me/919794620535');
 expect(url.searchParams.get('text')).toContain('A recruiter & team');
 expect(url.searchParams.get('text')).toContain('Build APIs + AI? Let’s discuss <scope>.');
 await page.getByLabel('Your message',{exact:true}).fill('Updated enquiry');
 await expect(page.locator('#contact-ready')).toBeHidden();
 await expect(link).not.toHaveAttribute('href');
});
